### ISSUE TITLE
Documentation Layout

### ISSUE THREAD

**Issue by MikhailZex** [spotDL/Proton#2]
A good documentation format/layout is super useful in achieving the aims of Proton.

**Comment by Mikhail-Zex** [comment]
Related to docs on spotdl, same layout to be used here. So just giving you the heads up @loftwah

**Comment by loftwah** [comment]
Roger that, cheers. I agree about the standard, I'll get something together for it for you to review.

**Comment by Mikhail-Zex** [comment]
sure, open a draft on spotDL/spotify-downloader, that way others can give in their inputs while you work on it, who knows? you might actually get some good ideas and cut down on some hard work.

+ join in on discord. almost everyone is there except you and @aasmpro
